/**
 * Auto-generated by scripts/download-espn-logos.mjs
 * Generated: 2026-02-24T13:22:50.142Z
 *
 * Maps team display names to their local logo paths.
 * Usage: import { getTeamLogo } from "@/src/lib/utils/team-logos";
 */

import manifest from "@/public/logos/manifest.json";

type LeagueSlug = "nba" | "nfl" | "mlb" | "nhl" | "ncaaf" | "ncaamb";

interface TeamInfo {
  id: string;
  displayName: string;
  shortName: string;
  abbreviation: string;
  location: string;
  nickname: string;
  color: string | null;
  alternateColor: string | null;
  logo: string | null;
  logoDark: string | null;
  localLogo: string;
  localLogoDark: string;
}

type Manifest = Record<LeagueSlug, Record<string, TeamInfo>>;

const teams = manifest as unknown as Manifest;

/**
 * Get the local logo path for a team.
 * @param league - League slug (nba, nfl, mlb, nhl, ncaaf, ncaamb)
 * @param teamName - Team display name (e.g., "Atlanta Hawks") or abbreviation (e.g., "ATL")
 * @param dark - Use dark variant (default: true for dark theme apps)
 * @returns Local logo path like "/logos/nba/atl-dark.png" or null if not found
 */
export function getTeamLogo(
  league: LeagueSlug,
  teamName: string,
  dark = true
): string | null {
  const leagueTeams = teams[league];
  if (!leagueTeams) return null;

  // Try direct abbreviation lookup first
  const abbr = teamName.toLowerCase();
  if (leagueTeams[abbr]) {
    const prefix = "/logos";
    return dark
      ? prefix + leagueTeams[abbr].localLogoDark
      : prefix + leagueTeams[abbr].localLogo;
  }

  // Fuzzy match by display name, short name, location, or nickname
  const needle = teamName.toLowerCase();
  for (const [, team] of Object.entries(leagueTeams)) {
    if (
      team.displayName.toLowerCase() === needle ||
      team.shortName.toLowerCase() === needle ||
      team.location.toLowerCase() === needle ||
      team.nickname.toLowerCase() === needle ||
      team.displayName.toLowerCase().includes(needle) ||
      needle.includes(team.shortName.toLowerCase())
    ) {
      const prefix = "/logos";
      return dark
        ? prefix + team.localLogoDark
        : prefix + team.localLogo;
    }
  }

  return null;
}

/**
 * Get team color (primary) for UI accents.
 */
export function getTeamColor(league: LeagueSlug, teamName: string): string | null {
  const leagueTeams = teams[league];
  if (!leagueTeams) return null;

  const abbr = teamName.toLowerCase();
  if (leagueTeams[abbr]) return leagueTeams[abbr].color;

  const needle = teamName.toLowerCase();
  for (const team of Object.values(leagueTeams)) {
    if (
      team.displayName.toLowerCase().includes(needle) ||
      needle.includes(team.shortName.toLowerCase())
    ) {
      return team.color;
    }
  }

  return null;
}

/**
 * Get all teams for a league.
 */
export function getLeagueTeams(league: LeagueSlug): TeamInfo[] {
  return Object.values(teams[league] ?? {});
}

export { teams as teamManifest };
export type { LeagueSlug, TeamInfo, Manifest };
